name: CI/CD Pipeline - Production

on:
  merge:
    branches:
      - master

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build:
    name: Production
    uses: ./.github/workflows/build.yml
    needs: ci
    with:
      ENVIRONMENT: production
    secrets: inherit

  deploy:
    name: Production
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      ENVIRONMENT: production
    secrets: inherit
