name: CI/CD Pipeline - Production

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: production
    secrets: inherit

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: production
    secrets: inherit
